name: synth
version: 0.0.1
description: >
  Simple, minimal, and efficient Dart web developement framework porting to  new Dart versions.
author: Paul Panks, forked by Jeremiah John M. Macariola <jjmmacariola@gmail.com>
homepage: https://github.com/ppanconi/synth